/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as CoachEspaceRouteImport } from './routes/coach.espace'
import { Route as CoachInscriptionRouteImport } from './routes/coach.inscription'
import { Route as CoachsIndexRouteImport } from './routes/coachs.index'
import { Route as CoachsIdRouteImport } from './routes/coachs.$id'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachEspaceRoute = CoachEspaceRouteImport.update({
  id: '/coach/espace',
  path: '/coach/espace',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachInscriptionRoute = CoachInscriptionRouteImport.update({
  id: '/coach/inscription',
  path: '/coach/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachsIndexRoute = CoachsIndexRouteImport.update({
  id: '/coachs/',
  path: '/coachs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachsIdRoute = CoachsIdRouteImport.update({
  id: '/coachs/$id',
  path: '/coachs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/programmes': typeof ProgrammesRoute
  '/coach/espace': typeof CoachEspaceRoute
  '/coach/inscription': typeof CoachInscriptionRoute
  '/coachs/$id': typeof CoachsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/coachs/': typeof CoachsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/programmes': typeof ProgrammesRoute
  '/coach/espace': typeof CoachEspaceRoute
  '/coach/inscription': typeof CoachInscriptionRoute
  '/coachs/$id': typeof CoachsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/coachs': typeof CoachsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/programmes': typeof ProgrammesRoute
  '/coach/espace': typeof CoachEspaceRoute
  '/coach/inscription': typeof CoachInscriptionRoute
  '/coachs/$id': typeof CoachsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/coachs/': typeof CoachsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/programmes'
    | '/coach/espace'
    | '/coach/inscription'
    | '/coachs/$id'
    | '/services/$slug'
    | '/coachs/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/programmes'
    | '/coach/espace'
    | '/coach/inscription'
    | '/coachs/$id'
    | '/services/$slug'
    | '/coachs'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/programmes'
    | '/coach/espace'
    | '/coach/inscription'
    | '/coachs/$id'
    | '/services/$slug'
    | '/coachs/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ProgrammesRoute: typeof ProgrammesRoute
  CoachEspaceRoute: typeof CoachEspaceRoute
  CoachInscriptionRoute: typeof CoachInscriptionRoute
  CoachsIdRoute: typeof CoachsIdRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  CoachsIndexRoute: typeof CoachsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/espace': {
      id: '/coach/espace'
      path: '/coach/espace'
      fullPath: '/coach/espace'
      preLoaderRoute: typeof CoachEspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/inscription': {
      id: '/coach/inscription'
      path: '/coach/inscription'
      fullPath: '/coach/inscription'
      preLoaderRoute: typeof CoachInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coachs/': {
      id: '/coachs/'
      path: '/coachs'
      fullPath: '/coachs/'
      preLoaderRoute: typeof CoachsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coachs/$id': {
      id: '/coachs/$id'
      path: '/coachs/$id'
      fullPath: '/coachs/$id'
      preLoaderRoute: typeof CoachsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ProgrammesRoute: ProgrammesRoute,
  CoachEspaceRoute: CoachEspaceRoute,
  CoachInscriptionRoute: CoachInscriptionRoute,
  CoachsIdRoute: CoachsIdRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  CoachsIndexRoute: CoachsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
